(define
	(problem sudoku_3)
	(:domain sudoku)
	(:init
		(= (value_of one) 1)
		(= (value_of two) 2)
		(= (value_of three) 3)
		(= (value_of four) 4)
		(= (value_of five) 5)
		(= (value_of six) 6)
		(= (value_of seven) 7)
		(= (value_of eight) 8)
		(= (value_of nine) 9)
		(= (value_of ten) A)
		(= (value_of eleven) B)
		(= (value_of twelve) C)
		(= (value_of thirteen) D)
		(= (value_of fourteen) E)
		(= (value_of fifteen) F)
		(= (value_of sixteen) G)
		(= (value_of seventeen) H)
		(= (value_of eighteen) I)
		(= (value_of nineteen) J)
		(= (value_of twenty) K)
		(= (value_of twenty-one) L)
		(= (value_of twenty-two) M)
		(= (value_of twenty-three) N)
		(= (value_of twenty-four) O)
		(= (value_of twenty-five) P)

		(= (cell_value one one) 0)
		(= (cell_value one two) 0)
		(= (cell_value one three) 0)
		(= (cell_value one four) E)
		(= (cell_value one five) 5)
		(= (cell_value one six) 0)
		(= (cell_value one seven) 4)
		(= (cell_value one eight) 0)
		(= (cell_value one nine) 0)
		(= (cell_value one ten) F)
		(= (cell_value one eleven) D)
		(= (cell_value one twelve) 0)
		(= (cell_value one thirteen) 0)
		(= (cell_value one fourteen) B)
		(= (cell_value one fifteen) 0)
		(= (cell_value one sixteen) 0)
		(= (cell_value one seventeen) K)
		(= (cell_value one eighteen) M)
		(= (cell_value one nineteen) G)
		(= (cell_value one twenty) 0)
		(= (cell_value one twenty-one) 0)
		(= (cell_value one twenty-two) 0)
		(= (cell_value one twenty-three) 0)
		(= (cell_value one twenty-four) 1)
		(= (cell_value one twenty-five) 0)

		(= (cell_value two one) 7)
		(= (cell_value two two) 0)
		(= (cell_value two three) 0)
		(= (cell_value two four) 0)
		(= (cell_value two five) 0)
		(= (cell_value two six) O)
		(= (cell_value two seven) 0)
		(= (cell_value two eight) 0)
		(= (cell_value two nine) 2)
		(= (cell_value two ten) 0)
		(= (cell_value two eleven) 0)
		(= (cell_value two twelve) 0)
		(= (cell_value two thirteen) G)
		(= (cell_value two fourteen) 0)
		(= (cell_value two fifteen) L)
		(= (cell_value two sixteen) 1)
		(= (cell_value two seventeen) 0)
		(= (cell_value two eighteen) C)
		(= (cell_value two nineteen) 6)
		(= (cell_value two twenty) 4)
		(= (cell_value two twenty-one) 0)
		(= (cell_value two twenty-two) 0)
		(= (cell_value two twenty-three) B)
		(= (cell_value two twenty-four) 3)
		(= (cell_value two twenty-five) 0)

		(= (cell_value three one) 1)
		(= (cell_value three two) P)
		(= (cell_value three three) 0)
		(= (cell_value three four) 0)
		(= (cell_value three five) 0)
		(= (cell_value three six) 0)
		(= (cell_value three seven) 0)
		(= (cell_value three eight) 0)
		(= (cell_value three nine) 0)
		(= (cell_value three ten) 0)
		(= (cell_value three eleven) I)
		(= (cell_value three twelve) 0)
		(= (cell_value three thirteen) 0)
		(= (cell_value three fourteen) 0)
		(= (cell_value three fifteen) K)
		(= (cell_value three sixteen) 0)
		(= (cell_value three seventeen) 0)
		(= (cell_value three eighteen) 0)
		(= (cell_value three nineteen) O)
		(= (cell_value three twenty) 0)
		(= (cell_value three twenty-one) 0)
		(= (cell_value three twenty-two) D)
		(= (cell_value three twenty-three) N)
		(= (cell_value three twenty-four) 2)
		(= (cell_value three twenty-five) 0)

		(= (cell_value four one) D)
		(= (cell_value four two) K)
		(= (cell_value four three) 0)
		(= (cell_value four four) M)
		(= (cell_value four five) 0)
		(= (cell_value four six) 0)
		(= (cell_value four seven) 0)
		(= (cell_value four eight) 0)
		(= (cell_value four nine) J)
		(= (cell_value four ten) 0)
		(= (cell_value four eleven) 1)
		(= (cell_value four twelve) H)
		(= (cell_value four thirteen) 0)
		(= (cell_value four fourteen) 0)
		(= (cell_value four fifteen) 0)
		(= (cell_value four sixteen) L)
		(= (cell_value four seventeen) 0)
		(= (cell_value four eighteen) 0)
		(= (cell_value four nineteen) I)
		(= (cell_value four twenty) 2)
		(= (cell_value four twenty-one) 9)
		(= (cell_value four twenty-two) G)
		(= (cell_value four twenty-three) 0)
		(= (cell_value four twenty-four) E)
		(= (cell_value four twenty-five) O)

		(= (cell_value five one) H)
		(= (cell_value five two) 0)
		(= (cell_value five three) L)
		(= (cell_value five four) 0)
		(= (cell_value five five) 0)
		(= (cell_value five six) 0)
		(= (cell_value five seven) G)
		(= (cell_value five eight) 0)
		(= (cell_value five nine) B)
		(= (cell_value five ten) 6)
		(= (cell_value five eleven) 8)
		(= (cell_value five twelve) 0)
		(= (cell_value five thirteen) 7)
		(= (cell_value five fourteen) F)
		(= (cell_value five fifteen) 0)
		(= (cell_value five sixteen) 9)
		(= (cell_value five seventeen) 5)
		(= (cell_value five eighteen) 0)
		(= (cell_value five nineteen) 0)
		(= (cell_value five twenty) 0)
		(= (cell_value five twenty-one) 0)
		(= (cell_value five twenty-two) 0)
		(= (cell_value five twenty-three) 0)
		(= (cell_value five twenty-four) 0)
		(= (cell_value five twenty-five) 4)

		(= (cell_value six one) 6)
		(= (cell_value six two) F)
		(= (cell_value six three) H)
		(= (cell_value six four) 0)
		(= (cell_value six five) 9)
		(= (cell_value six six) 5)
		(= (cell_value six seven) 0)
		(= (cell_value six eight) 0)
		(= (cell_value six nine) 0)
		(= (cell_value six ten) 0)
		(= (cell_value six eleven) 0)
		(= (cell_value six twelve) 4)
		(= (cell_value six thirteen) 0)
		(= (cell_value six fourteen) 0)
		(= (cell_value six fifteen) 0)
		(= (cell_value six sixteen) 0)
		(= (cell_value six seventeen) G)
		(= (cell_value six eighteen) 0)
		(= (cell_value six nineteen) 0)
		(= (cell_value six twenty) 0)
		(= (cell_value six twenty-one) 0)
		(= (cell_value six twenty-two) 8)
		(= (cell_value six twenty-three) 1)
		(= (cell_value six twenty-four) 0)
		(= (cell_value six twenty-five) 0)

		(= (cell_value seven one) 0)
		(= (cell_value seven two) 0)
		(= (cell_value seven three) 0)
		(= (cell_value seven four) 8)
		(= (cell_value seven five) 0)
		(= (cell_value seven six) 0)
		(= (cell_value seven seven) 0)
		(= (cell_value seven eight) 2)
		(= (cell_value seven nine) 0)
		(= (cell_value seven ten) 0)
		(= (cell_value seven eleven) N)
		(= (cell_value seven twelve) 0)
		(= (cell_value seven thirteen) 0)
		(= (cell_value seven fourteen) 0)
		(= (cell_value seven fifteen) 1)
		(= (cell_value seven sixteen) 6)
		(= (cell_value seven seventeen) 0)
		(= (cell_value seven eighteen) L)
		(= (cell_value seven nineteen) M)
		(= (cell_value seven twenty) 5)
		(= (cell_value seven twenty-one) 0)
		(= (cell_value seven twenty-two) 4)
		(= (cell_value seven twenty-three) 0)
		(= (cell_value seven twenty-four) 0)
		(= (cell_value seven twenty-five) 9)

		(= (cell_value eight one) P)
		(= (cell_value eight two) 4)
		(= (cell_value eight three) I)
		(= (cell_value eight four) 0)
		(= (cell_value eight five) 0)
		(= (cell_value eight six) 0)
		(= (cell_value eight seven) 0)
		(= (cell_value eight eight) D)
		(= (cell_value eight nine) 6)
		(= (cell_value eight ten) B)
		(= (cell_value eight eleven) J)
		(= (cell_value eight twelve) K)
		(= (cell_value eight thirteen) 9)
		(= (cell_value eight fourteen) 8)
		(= (cell_value eight fifteen) 0)
		(= (cell_value eight sixteen) 0)
		(= (cell_value eight seventeen) 0)
		(= (cell_value eight eighteen) 0)
		(= (cell_value eight nineteen) C)
		(= (cell_value eight twenty) N)
		(= (cell_value eight twenty-one) M)
		(= (cell_value eight twenty-two) 0)
		(= (cell_value eight twenty-three) 0)
		(= (cell_value eight twenty-four) 0)
		(= (cell_value eight twenty-five) 2)

		(= (cell_value nine one) N)
		(= (cell_value nine two) O)
		(= (cell_value nine three) 3)
		(= (cell_value nine four) 0)
		(= (cell_value nine five) 0)
		(= (cell_value nine six) 4)
		(= (cell_value nine seven) F)
		(= (cell_value nine eight) 1)
		(= (cell_value nine nine) I)
		(= (cell_value nine ten) 0)
		(= (cell_value nine eleven) P)
		(= (cell_value nine twelve) B)
		(= (cell_value nine thirteen) 0)
		(= (cell_value nine fourteen) 0)
		(= (cell_value nine fifteen) 0)
		(= (cell_value nine sixteen) 0)
		(= (cell_value nine seventeen) E)
		(= (cell_value nine eighteen) 0)
		(= (cell_value nine nineteen) 8)
		(= (cell_value nine twenty) 0)
		(= (cell_value nine twenty-one) J)
		(= (cell_value nine twenty-two) 0)
		(= (cell_value nine twenty-three) 0)
		(= (cell_value nine twenty-four) 0)
		(= (cell_value nine twenty-five) 0)

		(= (cell_value ten one) 0)
		(= (cell_value ten two) 0)
		(= (cell_value ten three) 0)
		(= (cell_value ten four) B)
		(= (cell_value ten five) 7)
		(= (cell_value ten six) N)
		(= (cell_value ten seven) E)
		(= (cell_value ten eight) 0)
		(= (cell_value ten nine) C)
		(= (cell_value ten ten) 0)
		(= (cell_value ten eleven) L)
		(= (cell_value ten twelve) G)
		(= (cell_value ten thirteen) F)
		(= (cell_value ten fourteen) H)
		(= (cell_value ten fifteen) 6)
		(= (cell_value ten sixteen) 0)
		(= (cell_value ten seventeen) 0)
		(= (cell_value ten eighteen) J)
		(= (cell_value ten nineteen) 2)
		(= (cell_value ten twenty) 0)
		(= (cell_value ten twenty-one) 0)
		(= (cell_value ten twenty-two) O)
		(= (cell_value ten twenty-three) K)
		(= (cell_value ten twenty-four) 0)
		(= (cell_value ten twenty-five) A)

		(= (cell_value eleven one) 0)
		(= (cell_value eleven two) 0)
		(= (cell_value eleven three) 9)
		(= (cell_value eleven four) 3)
		(= (cell_value eleven five) 2)
		(= (cell_value eleven six) 0)
		(= (cell_value eleven seven) M)
		(= (cell_value eleven eight) O)
		(= (cell_value eleven nine) 7)
		(= (cell_value eleven ten) 0)
		(= (cell_value eleven eleven) 0)
		(= (cell_value eleven twelve) 1)
		(= (cell_value eleven thirteen) 0)
		(= (cell_value eleven fourteen) 0)
		(= (cell_value eleven fifteen) 0)
		(= (cell_value eleven sixteen) B)
		(= (cell_value eleven seventeen) 0)
		(= (cell_value eleven eighteen) 0)
		(= (cell_value eleven nineteen) 4)
		(= (cell_value eleven twenty) F)
		(= (cell_value eleven twenty-one) 0)
		(= (cell_value eleven twenty-two) 0)
		(= (cell_value eleven twenty-three) 0)
		(= (cell_value eleven twenty-four) 0)
		(= (cell_value eleven twenty-five) 0)

		(= (cell_value twelve one) 0)
		(= (cell_value twelve two) 0)
		(= (cell_value twelve three) 0)
		(= (cell_value twelve four) D)
		(= (cell_value twelve five) 4)
		(= (cell_value twelve six) 0)
		(= (cell_value twelve seven) 0)
		(= (cell_value twelve eight) 0)
		(= (cell_value twelve nine) 0)
		(= (cell_value twelve ten) 0)
		(= (cell_value twelve eleven) 0)
		(= (cell_value twelve twelve) 0)
		(= (cell_value twelve thirteen) K)
		(= (cell_value twelve fourteen) 0)
		(= (cell_value twelve fifteen) 0)
		(= (cell_value twelve sixteen) 0)
		(= (cell_value twelve seventeen) C)
		(= (cell_value twelve eighteen) 3)
		(= (cell_value twelve nineteen) 0)
		(= (cell_value twelve twenty) 0)
		(= (cell_value twelve twenty-one) 0)
		(= (cell_value twelve twenty-two) A)
		(= (cell_value twelve twenty-three) 9)
		(= (cell_value twelve twenty-four) P)
		(= (cell_value twelve twenty-five) M)

		(= (cell_value thirteen one) 0)
		(= (cell_value thirteen two) 6)
		(= (cell_value thirteen three) 0)
		(= (cell_value thirteen four) 0)
		(= (cell_value thirteen five) 0)
		(= (cell_value thirteen six) 0)
		(= (cell_value thirteen seven) A)
		(= (cell_value thirteen eight) E)
		(= (cell_value thirteen nine) 0)
		(= (cell_value thirteen ten) 4)
		(= (cell_value thirteen eleven) 5)
		(= (cell_value thirteen twelve) 0)
		(= (cell_value thirteen thirteen) 0)
		(= (cell_value thirteen fourteen) 0)
		(= (cell_value thirteen fifteen) D)
		(= (cell_value thirteen sixteen) 0)
		(= (cell_value thirteen seventeen) 0)
		(= (cell_value thirteen eighteen) K)
		(= (cell_value thirteen nineteen) 0)
		(= (cell_value thirteen twenty) 0)
		(= (cell_value thirteen twenty-one) H)
		(= (cell_value thirteen twenty-two) 0)
		(= (cell_value thirteen twenty-three) C)
		(= (cell_value thirteen twenty-four) 0)
		(= (cell_value thirteen twenty-five) 0)

		(= (cell_value fourteen one) M)
		(= (cell_value fourteen two) 0)
		(= (cell_value fourteen three) 7)
		(= (cell_value fourteen four) K)
		(= (cell_value fourteen five) O)
		(= (cell_value fourteen six) 0)
		(= (cell_value fourteen seven) 0)
		(= (cell_value fourteen eight) F)
		(= (cell_value fourteen nine) 0)
		(= (cell_value fourteen ten) 0)
		(= (cell_value fourteen eleven) 2)
		(= (cell_value fourteen twelve) P)
		(= (cell_value fourteen thirteen) H)
		(= (cell_value fourteen fourteen) 0)
		(= (cell_value fourteen fifteen) A)
		(= (cell_value fourteen sixteen) 0)
		(= (cell_value fourteen seventeen) 0)
		(= (cell_value fourteen eighteen) 0)
		(= (cell_value fourteen nineteen) 0)
		(= (cell_value fourteen twenty) 6)
		(= (cell_value fourteen twenty-one) 0)
		(= (cell_value fourteen twenty-two) 0)
		(= (cell_value fourteen twenty-three) 0)
		(= (cell_value fourteen twenty-four) B)
		(= (cell_value fourteen twenty-five) 0)

		(= (cell_value fifteen one) 0)
		(= (cell_value fifteen two) H)
		(= (cell_value fifteen three) 0)
		(= (cell_value fifteen four) 0)
		(= (cell_value fifteen five) P)
		(= (cell_value fifteen six) L)
		(= (cell_value fifteen seven) 0)
		(= (cell_value fifteen eight) 0)
		(= (cell_value fifteen nine) 0)
		(= (cell_value fifteen ten) 0)
		(= (cell_value fifteen eleven) 0)
		(= (cell_value fifteen twelve) I)
		(= (cell_value fifteen thirteen) 3)
		(= (cell_value fifteen fourteen) 0)
		(= (cell_value fifteen fifteen) 9)
		(= (cell_value fifteen sixteen) G)
		(= (cell_value fifteen seventeen) M)
		(= (cell_value fifteen eighteen) 0)
		(= (cell_value fifteen nineteen) N)
		(= (cell_value fifteen twenty) 0)
		(= (cell_value fifteen twenty-one) O)
		(= (cell_value fifteen twenty-two) 0)
		(= (cell_value fifteen twenty-three) F)
		(= (cell_value fifteen twenty-four) 4)
		(= (cell_value fifteen twenty-five) 0)

		(= (cell_value sixteen one) 0)
		(= (cell_value sixteen two) 0)
		(= (cell_value sixteen three) K)
		(= (cell_value sixteen four) 0)
		(= (cell_value sixteen five) 0)
		(= (cell_value sixteen six) 7)
		(= (cell_value sixteen seven) 0)
		(= (cell_value sixteen eight) 0)
		(= (cell_value sixteen nine) 4)
		(= (cell_value sixteen ten) 0)
		(= (cell_value sixteen eleven) E)
		(= (cell_value sixteen twelve) 0)
		(= (cell_value sixteen thirteen) 0)
		(= (cell_value sixteen fourteen) D)
		(= (cell_value sixteen fifteen) 0)
		(= (cell_value sixteen sixteen) P)
		(= (cell_value sixteen seventeen) 0)
		(= (cell_value sixteen eighteen) N)
		(= (cell_value sixteen nineteen) A)
		(= (cell_value sixteen twenty) 0)
		(= (cell_value sixteen twenty-one) 0)
		(= (cell_value sixteen twenty-two) B)
		(= (cell_value sixteen twenty-three) 8)
		(= (cell_value sixteen twenty-four) 9)
		(= (cell_value sixteen twenty-five) G)

		(= (cell_value seventeen one) F)
		(= (cell_value seventeen two) 0)
		(= (cell_value seventeen three) 0)
		(= (cell_value seventeen four) 0)
		(= (cell_value seventeen five) 0)
		(= (cell_value seventeen six) 0)
		(= (cell_value seventeen seven) P)
		(= (cell_value seventeen eight) 0)
		(= (cell_value seventeen nine) A)
		(= (cell_value seventeen ten) I)
		(= (cell_value seventeen eleven) 0)
		(= (cell_value seventeen twelve) 9)
		(= (cell_value seventeen thirteen) 2)
		(= (cell_value seventeen fourteen) 0)
		(= (cell_value seventeen fifteen) 0)
		(= (cell_value seventeen sixteen) O)
		(= (cell_value seventeen seventeen) D)
		(= (cell_value seventeen eighteen) 4)
		(= (cell_value seventeen nineteen) 0)
		(= (cell_value seventeen twenty) J)
		(= (cell_value seventeen twenty-one) 3)
		(= (cell_value seventeen twenty-two) K)
		(= (cell_value seventeen twenty-three) 6)
		(= (cell_value seventeen twenty-four) 5)
		(= (cell_value seventeen twenty-five) 7)

		(= (cell_value eighteen one) 0)
		(= (cell_value eighteen two) 2)
		(= (cell_value eighteen three) 0)
		(= (cell_value eighteen four) 0)
		(= (cell_value eighteen five) 0)
		(= (cell_value eighteen six) 0)
		(= (cell_value eighteen seven) 0)
		(= (cell_value eighteen eight) L)
		(= (cell_value eighteen nine) 0)
		(= (cell_value eighteen ten) M)
		(= (cell_value eighteen eleven) F)
		(= (cell_value eighteen twelve) 0)
		(= (cell_value eighteen thirteen) P)
		(= (cell_value eighteen fourteen) 0)
		(= (cell_value eighteen fifteen) 0)
		(= (cell_value eighteen sixteen) 0)
		(= (cell_value eighteen seventeen) 9)
		(= (cell_value eighteen eighteen) 1)
		(= (cell_value eighteen nineteen) 0)
		(= (cell_value eighteen twenty) H)
		(= (cell_value eighteen twenty-one) A)
		(= (cell_value eighteen twenty-two) 0)
		(= (cell_value eighteen twenty-three) 0)
		(= (cell_value eighteen twenty-four) 0)
		(= (cell_value eighteen twenty-five) J)

		(= (cell_value nineteen one) O)
		(= (cell_value nineteen two) 0)
		(= (cell_value nineteen three) 0)
		(= (cell_value nineteen four) 0)
		(= (cell_value nineteen five) A)
		(= (cell_value nineteen six) 3)
		(= (cell_value nineteen seven) 0)
		(= (cell_value nineteen eight) K)
		(= (cell_value nineteen nine) N)
		(= (cell_value nineteen ten) 0)
		(= (cell_value nineteen eleven) 0)
		(= (cell_value nineteen twelve) 0)
		(= (cell_value nineteen thirteen) 0)
		(= (cell_value nineteen fourteen) 5)
		(= (cell_value nineteen fifteen) J)
		(= (cell_value nineteen sixteen) E)
		(= (cell_value nineteen seventeen) 0)
		(= (cell_value nineteen eighteen) 0)
		(= (cell_value nineteen nineteen) 0)
		(= (cell_value nineteen twenty) 0)
		(= (cell_value nineteen twenty-one) 0)
		(= (cell_value nineteen twenty-two) 0)
		(= (cell_value nineteen twenty-three) 0)
		(= (cell_value nineteen twenty-four) 0)
		(= (cell_value nineteen twenty-five) H)

		(= (cell_value twenty one) 0)
		(= (cell_value twenty two) 3)
		(= (cell_value twenty three) 0)
		(= (cell_value twenty four) J)
		(= (cell_value twenty five) M)
		(= (cell_value twenty six) F)
		(= (cell_value twenty seven) 1)
		(= (cell_value twenty eight) 8)
		(= (cell_value twenty nine) 0)
		(= (cell_value twenty ten) D)
		(= (cell_value twenty eleven) 0)
		(= (cell_value twenty twelve) 0)
		(= (cell_value twenty thirteen) A)
		(= (cell_value twenty fourteen) K)
		(= (cell_value twenty fifteen) H)
		(= (cell_value twenty sixteen) 0)
		(= (cell_value twenty seventeen) 6)
		(= (cell_value twenty eighteen) 0)
		(= (cell_value twenty nineteen) B)
		(= (cell_value twenty twenty) 0)
		(= (cell_value twenty twenty-one) E)
		(= (cell_value twenty twenty-two) 0)
		(= (cell_value twenty twenty-three) I)
		(= (cell_value twenty twenty-four) 0)
		(= (cell_value twenty twenty-five) L)

		(= (cell_value twenty-one one) 0)
		(= (cell_value twenty-one two) 0)
		(= (cell_value twenty-one three) E)
		(= (cell_value twenty-one four) 0)
		(= (cell_value twenty-one five) 0)
		(= (cell_value twenty-one six) 2)
		(= (cell_value twenty-one seven) 0)
		(= (cell_value twenty-one eight) 0)
		(= (cell_value twenty-one nine) 0)
		(= (cell_value twenty-one ten) 5)
		(= (cell_value twenty-one eleven) 0)
		(= (cell_value twenty-one twelve) 0)
		(= (cell_value twenty-one thirteen) 0)
		(= (cell_value twenty-one fourteen) G)
		(= (cell_value twenty-one fifteen) 0)
		(= (cell_value twenty-one sixteen) 0)
		(= (cell_value twenty-one seventeen) 0)
		(= (cell_value twenty-one eighteen) 0)
		(= (cell_value twenty-one nineteen) P)
		(= (cell_value twenty-one twenty) 0)
		(= (cell_value twenty-one twenty-one) K)
		(= (cell_value twenty-one twenty-two) 1)
		(= (cell_value twenty-one twenty-three) L)
		(= (cell_value twenty-one twenty-four) 0)
		(= (cell_value twenty-one twenty-five) 0)

		(= (cell_value twenty-two one) 0)
		(= (cell_value twenty-two two) 0)
		(= (cell_value twenty-two three) 0)
		(= (cell_value twenty-two four) C)
		(= (cell_value twenty-two five) 0)
		(= (cell_value twenty-two six) 0)
		(= (cell_value twenty-two seven) 0)
		(= (cell_value twenty-two eight) G)
		(= (cell_value twenty-two nine) E)
		(= (cell_value twenty-two ten) 0)
		(= (cell_value twenty-two eleven) 0)
		(= (cell_value twenty-two twelve) F)
		(= (cell_value twenty-two thirteen) 0)
		(= (cell_value twenty-two fourteen) J)
		(= (cell_value twenty-two fifteen) 0)
		(= (cell_value twenty-two sixteen) H)
		(= (cell_value twenty-two seventeen) 0)
		(= (cell_value twenty-two eighteen) 5)
		(= (cell_value twenty-two nineteen) 0)
		(= (cell_value twenty-two twenty) 0)
		(= (cell_value twenty-two twenty-one) 0)
		(= (cell_value twenty-two twenty-two) 0)
		(= (cell_value twenty-two twenty-three) 0)
		(= (cell_value twenty-two twenty-four) 0)
		(= (cell_value twenty-two twenty-five) 0)

		(= (cell_value twenty-three one) 0)
		(= (cell_value twenty-three two) 0)
		(= (cell_value twenty-three three) M)
		(= (cell_value twenty-three four) 0)
		(= (cell_value twenty-three five) K)
		(= (cell_value twenty-three six) J)
		(= (cell_value twenty-three seven) 6)
		(= (cell_value twenty-three eight) I)
		(= (cell_value twenty-three nine) 8)
		(= (cell_value twenty-three ten) 0)
		(= (cell_value twenty-three eleven) A)
		(= (cell_value twenty-three twelve) O)
		(= (cell_value twenty-three thirteen) 0)
		(= (cell_value twenty-three fourteen) L)
		(= (cell_value twenty-three fifteen) 0)
		(= (cell_value twenty-three sixteen) C)
		(= (cell_value twenty-three seventeen) 0)
		(= (cell_value twenty-three eighteen) B)
		(= (cell_value twenty-three nineteen) F)
		(= (cell_value twenty-three twenty) 0)
		(= (cell_value twenty-three twenty-one) 0)
		(= (cell_value twenty-three twenty-two) 5)
		(= (cell_value twenty-three twenty-three) 0)
		(= (cell_value twenty-three twenty-four) 0)
		(= (cell_value twenty-three twenty-five) 0)

		(= (cell_value twenty-four one) B)
		(= (cell_value twenty-four two) 5)
		(= (cell_value twenty-four three) 0)
		(= (cell_value twenty-four four) 0)
		(= (cell_value twenty-four five) 0)
		(= (cell_value twenty-four six) 0)
		(= (cell_value twenty-four seven) 7)
		(= (cell_value twenty-four eight) 0)
		(= (cell_value twenty-four nine) 0)
		(= (cell_value twenty-four ten) 9)
		(= (cell_value twenty-four eleven) 0)
		(= (cell_value twenty-four twelve) 0)
		(= (cell_value twenty-four thirteen) 8)
		(= (cell_value twenty-four fourteen) 0)
		(= (cell_value twenty-four fifteen) P)
		(= (cell_value twenty-four sixteen) 2)
		(= (cell_value twenty-four seventeen) L)
		(= (cell_value twenty-four eighteen) 0)
		(= (cell_value twenty-four nineteen) 0)
		(= (cell_value twenty-four twenty) 0)
		(= (cell_value twenty-four twenty-one) 0)
		(= (cell_value twenty-four twenty-two) F)
		(= (cell_value twenty-four twenty-three) O)
		(= (cell_value twenty-four twenty-four) 0)
		(= (cell_value twenty-four twenty-five) I)

		(= (cell_value twenty-five one) 0)
		(= (cell_value twenty-five two) 0)
		(= (cell_value twenty-five three) 0)
		(= (cell_value twenty-five four) P)
		(= (cell_value twenty-five five) 0)
		(= (cell_value twenty-five six) 0)
		(= (cell_value twenty-five seven) 0)
		(= (cell_value twenty-five eight) 0)
		(= (cell_value twenty-five nine) 0)
		(= (cell_value twenty-five ten) O)
		(= (cell_value twenty-five eleven) 4)
		(= (cell_value twenty-five twelve) 7)
		(= (cell_value twenty-five thirteen) I)
		(= (cell_value twenty-five fourteen) 0)
		(= (cell_value twenty-five fifteen) 0)
		(= (cell_value twenty-five sixteen) J)
		(= (cell_value twenty-five seventeen) 0)
		(= (cell_value twenty-five eighteen) 0)
		(= (cell_value twenty-five nineteen) 0)
		(= (cell_value twenty-five twenty) 0)
		(= (cell_value twenty-five twenty-one) 2)
		(= (cell_value twenty-five twenty-two) C)
		(= (cell_value twenty-five twenty-three) 0)
		(= (cell_value twenty-five twenty-four) 0)
		(= (cell_value twenty-five twenty-five) 0)

		(value_assigned one four)
		(value_assigned one five)
		(value_assigned one seven)
		(value_assigned one ten)
		(value_assigned one eleven)
		(value_assigned one fourteen)
		(value_assigned one seventeen)
		(value_assigned one eighteen)
		(value_assigned one nineteen)
		(value_assigned one twenty-four)

		(value_assigned two one)
		(value_assigned two six)
		(value_assigned two nine)
		(value_assigned two thirteen)
		(value_assigned two fifteen)
		(value_assigned two sixteen)
		(value_assigned two eighteen)
		(value_assigned two nineteen)
		(value_assigned two twenty)
		(value_assigned two twenty-three)
		(value_assigned two twenty-four)

		(value_assigned three one)
		(value_assigned three two)
		(value_assigned three eleven)
		(value_assigned three fifteen)
		(value_assigned three nineteen)
		(value_assigned three twenty-two)
		(value_assigned three twenty-three)
		(value_assigned three twenty-four)

		(value_assigned four one)
		(value_assigned four two)
		(value_assigned four four)
		(value_assigned four nine)
		(value_assigned four eleven)
		(value_assigned four twelve)
		(value_assigned four sixteen)
		(value_assigned four nineteen)
		(value_assigned four twenty)
		(value_assigned four twenty-one)
		(value_assigned four twenty-two)
		(value_assigned four twenty-four)
		(value_assigned four twenty-five)

		(value_assigned five one)
		(value_assigned five three)
		(value_assigned five seven)
		(value_assigned five nine)
		(value_assigned five ten)
		(value_assigned five eleven)
		(value_assigned five thirteen)
		(value_assigned five fourteen)
		(value_assigned five sixteen)
		(value_assigned five seventeen)
		(value_assigned five twenty-five)

		(value_assigned six one)
		(value_assigned six two)
		(value_assigned six three)
		(value_assigned six five)
		(value_assigned six six)
		(value_assigned six twelve)
		(value_assigned six seventeen)
		(value_assigned six twenty-two)
		(value_assigned six twenty-three)

		(value_assigned seven four)
		(value_assigned seven eight)
		(value_assigned seven eleven)
		(value_assigned seven fifteen)
		(value_assigned seven sixteen)
		(value_assigned seven eighteen)
		(value_assigned seven nineteen)
		(value_assigned seven twenty)
		(value_assigned seven twenty-two)
		(value_assigned seven twenty-five)

		(value_assigned eight one)
		(value_assigned eight two)
		(value_assigned eight three)
		(value_assigned eight eight)
		(value_assigned eight nine)
		(value_assigned eight ten)
		(value_assigned eight eleven)
		(value_assigned eight twelve)
		(value_assigned eight thirteen)
		(value_assigned eight fourteen)
		(value_assigned eight nineteen)
		(value_assigned eight twenty)
		(value_assigned eight twenty-one)
		(value_assigned eight twenty-five)

		(value_assigned nine one)
		(value_assigned nine two)
		(value_assigned nine three)
		(value_assigned nine six)
		(value_assigned nine seven)
		(value_assigned nine eight)
		(value_assigned nine nine)
		(value_assigned nine eleven)
		(value_assigned nine twelve)
		(value_assigned nine seventeen)
		(value_assigned nine nineteen)
		(value_assigned nine twenty-one)

		(value_assigned ten four)
		(value_assigned ten five)
		(value_assigned ten six)
		(value_assigned ten seven)
		(value_assigned ten nine)
		(value_assigned ten eleven)
		(value_assigned ten twelve)
		(value_assigned ten thirteen)
		(value_assigned ten fourteen)
		(value_assigned ten fifteen)
		(value_assigned ten eighteen)
		(value_assigned ten nineteen)
		(value_assigned ten twenty-two)
		(value_assigned ten twenty-three)
		(value_assigned ten twenty-five)

		(value_assigned eleven three)
		(value_assigned eleven four)
		(value_assigned eleven five)
		(value_assigned eleven seven)
		(value_assigned eleven eight)
		(value_assigned eleven nine)
		(value_assigned eleven twelve)
		(value_assigned eleven sixteen)
		(value_assigned eleven nineteen)
		(value_assigned eleven twenty)

		(value_assigned twelve four)
		(value_assigned twelve five)
		(value_assigned twelve thirteen)
		(value_assigned twelve seventeen)
		(value_assigned twelve eighteen)
		(value_assigned twelve twenty-two)
		(value_assigned twelve twenty-three)
		(value_assigned twelve twenty-four)
		(value_assigned twelve twenty-five)

		(value_assigned thirteen two)
		(value_assigned thirteen seven)
		(value_assigned thirteen eight)
		(value_assigned thirteen ten)
		(value_assigned thirteen eleven)
		(value_assigned thirteen fifteen)
		(value_assigned thirteen eighteen)
		(value_assigned thirteen twenty-one)
		(value_assigned thirteen twenty-three)

		(value_assigned fourteen one)
		(value_assigned fourteen three)
		(value_assigned fourteen four)
		(value_assigned fourteen five)
		(value_assigned fourteen eight)
		(value_assigned fourteen eleven)
		(value_assigned fourteen twelve)
		(value_assigned fourteen thirteen)
		(value_assigned fourteen fifteen)
		(value_assigned fourteen twenty)
		(value_assigned fourteen twenty-four)

		(value_assigned fifteen two)
		(value_assigned fifteen five)
		(value_assigned fifteen six)
		(value_assigned fifteen twelve)
		(value_assigned fifteen thirteen)
		(value_assigned fifteen fifteen)
		(value_assigned fifteen sixteen)
		(value_assigned fifteen seventeen)
		(value_assigned fifteen nineteen)
		(value_assigned fifteen twenty-one)
		(value_assigned fifteen twenty-three)
		(value_assigned fifteen twenty-four)

		(value_assigned sixteen three)
		(value_assigned sixteen six)
		(value_assigned sixteen nine)
		(value_assigned sixteen eleven)
		(value_assigned sixteen fourteen)
		(value_assigned sixteen sixteen)
		(value_assigned sixteen eighteen)
		(value_assigned sixteen nineteen)
		(value_assigned sixteen twenty-two)
		(value_assigned sixteen twenty-three)
		(value_assigned sixteen twenty-four)
		(value_assigned sixteen twenty-five)

		(value_assigned seventeen one)
		(value_assigned seventeen seven)
		(value_assigned seventeen nine)
		(value_assigned seventeen ten)
		(value_assigned seventeen twelve)
		(value_assigned seventeen thirteen)
		(value_assigned seventeen sixteen)
		(value_assigned seventeen seventeen)
		(value_assigned seventeen eighteen)
		(value_assigned seventeen twenty)
		(value_assigned seventeen twenty-one)
		(value_assigned seventeen twenty-two)
		(value_assigned seventeen twenty-three)
		(value_assigned seventeen twenty-four)
		(value_assigned seventeen twenty-five)

		(value_assigned eighteen two)
		(value_assigned eighteen eight)
		(value_assigned eighteen ten)
		(value_assigned eighteen eleven)
		(value_assigned eighteen thirteen)
		(value_assigned eighteen seventeen)
		(value_assigned eighteen eighteen)
		(value_assigned eighteen twenty)
		(value_assigned eighteen twenty-one)
		(value_assigned eighteen twenty-five)

		(value_assigned nineteen one)
		(value_assigned nineteen five)
		(value_assigned nineteen six)
		(value_assigned nineteen eight)
		(value_assigned nineteen nine)
		(value_assigned nineteen fourteen)
		(value_assigned nineteen fifteen)
		(value_assigned nineteen sixteen)
		(value_assigned nineteen twenty-five)

		(value_assigned twenty two)
		(value_assigned twenty four)
		(value_assigned twenty five)
		(value_assigned twenty six)
		(value_assigned twenty seven)
		(value_assigned twenty eight)
		(value_assigned twenty ten)
		(value_assigned twenty thirteen)
		(value_assigned twenty fourteen)
		(value_assigned twenty fifteen)
		(value_assigned twenty seventeen)
		(value_assigned twenty nineteen)
		(value_assigned twenty twenty-one)
		(value_assigned twenty twenty-three)
		(value_assigned twenty twenty-five)

		(value_assigned twenty-one three)
		(value_assigned twenty-one six)
		(value_assigned twenty-one ten)
		(value_assigned twenty-one fourteen)
		(value_assigned twenty-one nineteen)
		(value_assigned twenty-one twenty-one)
		(value_assigned twenty-one twenty-two)
		(value_assigned twenty-one twenty-three)

		(value_assigned twenty-two four)
		(value_assigned twenty-two eight)
		(value_assigned twenty-two nine)
		(value_assigned twenty-two twelve)
		(value_assigned twenty-two fourteen)
		(value_assigned twenty-two sixteen)
		(value_assigned twenty-two eighteen)

		(value_assigned twenty-three three)
		(value_assigned twenty-three five)
		(value_assigned twenty-three six)
		(value_assigned twenty-three seven)
		(value_assigned twenty-three eight)
		(value_assigned twenty-three nine)
		(value_assigned twenty-three eleven)
		(value_assigned twenty-three twelve)
		(value_assigned twenty-three fourteen)
		(value_assigned twenty-three sixteen)
		(value_assigned twenty-three eighteen)
		(value_assigned twenty-three nineteen)
		(value_assigned twenty-three twenty-two)

		(value_assigned twenty-four one)
		(value_assigned twenty-four two)
		(value_assigned twenty-four seven)
		(value_assigned twenty-four ten)
		(value_assigned twenty-four thirteen)
		(value_assigned twenty-four fifteen)
		(value_assigned twenty-four sixteen)
		(value_assigned twenty-four seventeen)
		(value_assigned twenty-four twenty-two)
		(value_assigned twenty-four twenty-three)
		(value_assigned twenty-four twenty-five)

		(value_assigned twenty-five four)
		(value_assigned twenty-five ten)
		(value_assigned twenty-five eleven)
		(value_assigned twenty-five twelve)
		(value_assigned twenty-five thirteen)
		(value_assigned twenty-five sixteen)
		(value_assigned twenty-five twenty-one)
		(value_assigned twenty-five twenty-two)

	)

	(:goal (and
		(value_assigned one one)
		(value_assigned one two)
		(value_assigned one three)
		(value_assigned one four)
		(value_assigned one five)
		(value_assigned one six)
		(value_assigned one seven)
		(value_assigned one eight)
		(value_assigned one nine)

		(value_assigned one ten)
		(value_assigned one eleven)
		(value_assigned one twelve)
		(value_assigned one thirteen)
		(value_assigned one fourteen)
		(value_assigned one fifteen)
		(value_assigned one sixteen)
		(value_assigned one seventeen)
		(value_assigned one eighteen)
		(value_assigned one nineteen)
		(value_assigned one twenty)
		(value_assigned one twenty-one)
		(value_assigned one twenty-two)
		(value_assigned one twenty-three)
		(value_assigned one twenty-four)
		(value_assigned one twenty-five)
		(value_assigned two one)
		(value_assigned two two)
		(value_assigned two three)
		(value_assigned two four)
		(value_assigned two five)
		(value_assigned two six)
		(value_assigned two seven)
		(value_assigned two eight)
		(value_assigned two nine)

		(value_assigned two ten)
		(value_assigned two eleven)
		(value_assigned two twelve)
		(value_assigned two thirteen)
		(value_assigned two fourteen)
		(value_assigned two fifteen)
		(value_assigned two sixteen)
		(value_assigned two seventeen)
		(value_assigned two eighteen)
		(value_assigned two nineteen)
		(value_assigned two twenty)
		(value_assigned two twenty-one)
		(value_assigned two twenty-two)
		(value_assigned two twenty-three)
		(value_assigned two twenty-four)
		(value_assigned two twenty-five)
		(value_assigned three one)
		(value_assigned three two)
		(value_assigned three three)
		(value_assigned three four)
		(value_assigned three five)
		(value_assigned three six)
		(value_assigned three seven)
		(value_assigned three eight)
		(value_assigned three nine)

		(value_assigned three ten)
		(value_assigned three eleven)
		(value_assigned three twelve)
		(value_assigned three thirteen)
		(value_assigned three fourteen)
		(value_assigned three fifteen)
		(value_assigned three sixteen)
		(value_assigned three seventeen)
		(value_assigned three eighteen)
		(value_assigned three nineteen)
		(value_assigned three twenty)
		(value_assigned three twenty-one)
		(value_assigned three twenty-two)
		(value_assigned three twenty-three)
		(value_assigned three twenty-four)
		(value_assigned three twenty-five)
		(value_assigned four one)
		(value_assigned four two)
		(value_assigned four three)
		(value_assigned four four)
		(value_assigned four five)
		(value_assigned four six)
		(value_assigned four seven)
		(value_assigned four eight)
		(value_assigned four nine)

		(value_assigned four ten)
		(value_assigned four eleven)
		(value_assigned four twelve)
		(value_assigned four thirteen)
		(value_assigned four fourteen)
		(value_assigned four fifteen)
		(value_assigned four sixteen)
		(value_assigned four seventeen)
		(value_assigned four eighteen)
		(value_assigned four nineteen)
		(value_assigned four twenty)
		(value_assigned four twenty-one)
		(value_assigned four twenty-two)
		(value_assigned four twenty-three)
		(value_assigned four twenty-four)
		(value_assigned four twenty-five)
		(value_assigned five one)
		(value_assigned five two)
		(value_assigned five three)
		(value_assigned five four)
		(value_assigned five five)
		(value_assigned five six)
		(value_assigned five seven)
		(value_assigned five eight)
		(value_assigned five nine)

		(value_assigned five ten)
		(value_assigned five eleven)
		(value_assigned five twelve)
		(value_assigned five thirteen)
		(value_assigned five fourteen)
		(value_assigned five fifteen)
		(value_assigned five sixteen)
		(value_assigned five seventeen)
		(value_assigned five eighteen)
		(value_assigned five nineteen)
		(value_assigned five twenty)
		(value_assigned five twenty-one)
		(value_assigned five twenty-two)
		(value_assigned five twenty-three)
		(value_assigned five twenty-four)
		(value_assigned five twenty-five)
		(value_assigned six one)
		(value_assigned six two)
		(value_assigned six three)
		(value_assigned six four)
		(value_assigned six five)
		(value_assigned six six)
		(value_assigned six seven)
		(value_assigned six eight)
		(value_assigned six nine)

		(value_assigned six ten)
		(value_assigned six eleven)
		(value_assigned six twelve)
		(value_assigned six thirteen)
		(value_assigned six fourteen)
		(value_assigned six fifteen)
		(value_assigned six sixteen)
		(value_assigned six seventeen)
		(value_assigned six eighteen)
		(value_assigned six nineteen)
		(value_assigned six twenty)
		(value_assigned six twenty-one)
		(value_assigned six twenty-two)
		(value_assigned six twenty-three)
		(value_assigned six twenty-four)
		(value_assigned six twenty-five)
		(value_assigned seven one)
		(value_assigned seven two)
		(value_assigned seven three)
		(value_assigned seven four)
		(value_assigned seven five)
		(value_assigned seven six)
		(value_assigned seven seven)
		(value_assigned seven eight)
		(value_assigned seven nine)

		(value_assigned seven ten)
		(value_assigned seven eleven)
		(value_assigned seven twelve)
		(value_assigned seven thirteen)
		(value_assigned seven fourteen)
		(value_assigned seven fifteen)
		(value_assigned seven sixteen)
		(value_assigned seven seventeen)
		(value_assigned seven eighteen)
		(value_assigned seven nineteen)
		(value_assigned seven twenty)
		(value_assigned seven twenty-one)
		(value_assigned seven twenty-two)
		(value_assigned seven twenty-three)
		(value_assigned seven twenty-four)
		(value_assigned seven twenty-five)
		(value_assigned eight one)
		(value_assigned eight two)
		(value_assigned eight three)
		(value_assigned eight four)
		(value_assigned eight five)
		(value_assigned eight six)
		(value_assigned eight seven)
		(value_assigned eight eight)
		(value_assigned eight nine)

		(value_assigned eight ten)
		(value_assigned eight eleven)
		(value_assigned eight twelve)
		(value_assigned eight thirteen)
		(value_assigned eight fourteen)
		(value_assigned eight fifteen)
		(value_assigned eight sixteen)
		(value_assigned eight seventeen)
		(value_assigned eight eighteen)
		(value_assigned eight nineteen)
		(value_assigned eight twenty)
		(value_assigned eight twenty-one)
		(value_assigned eight twenty-two)
		(value_assigned eight twenty-three)
		(value_assigned eight twenty-four)
		(value_assigned eight twenty-five)
		(value_assigned nine one)
		(value_assigned nine two)
		(value_assigned nine three)
		(value_assigned nine four)
		(value_assigned nine five)
		(value_assigned nine six)
		(value_assigned nine seven)
		(value_assigned nine eight)
		(value_assigned nine nine))
		(value_assigned nine ten)
		(value_assigned nine eleven)
		(value_assigned nine twelve)
		(value_assigned nine thirteen)
		(value_assigned nine fourteen)
		(value_assigned nine fifteen)
		(value_assigned nine sixteen)
		(value_assigned nine seventeen)
		(value_assigned nine eighteen)
		(value_assigned nine nineteen)
		(value_assigned nine twenty)
		(value_assigned nine twenty-one)
		(value_assigned nine twenty-two)
		(value_assigned nine twenty-three)
		(value_assigned nine twenty-four)
		(value_assigned nine twenty-five)
		(value_assigned ten one)
		(value_assigned ten two)
		(value_assigned ten three)
		(value_assigned ten four)
		(value_assigned ten five)
		(value_assigned ten six)
		(value_assigned ten seven)
		(value_assigned ten eight)
		(value_assigned ten nine)

		(value_assigned ten ten)
		(value_assigned ten eleven)
		(value_assigned ten twelve)
		(value_assigned ten thirteen)
		(value_assigned ten fourteen)
		(value_assigned ten fifteen)
		(value_assigned ten sixteen)
		(value_assigned ten seventeen)
		(value_assigned ten eighteen)
		(value_assigned ten nineteen)
		(value_assigned ten twenty)
		(value_assigned ten twenty-one)
		(value_assigned ten twenty-two)
		(value_assigned ten twenty-three)
		(value_assigned ten twenty-four)
		(value_assigned ten twenty-five)
		(value_assigned eleven one)
		(value_assigned eleven two)
		(value_assigned eleven three)
		(value_assigned eleven four)
		(value_assigned eleven five)
		(value_assigned eleven six)
		(value_assigned eleven seven)
		(value_assigned eleven eight)
		(value_assigned eleven nine)

		(value_assigned eleven ten)
		(value_assigned eleven eleven)
		(value_assigned eleven twelve)
		(value_assigned eleven thirteen)
		(value_assigned eleven fourteen)
		(value_assigned eleven fifteen)
		(value_assigned eleven sixteen)
		(value_assigned eleven seventeen)
		(value_assigned eleven eighteen)
		(value_assigned eleven nineteen)
		(value_assigned eleven twenty)
		(value_assigned eleven twenty-one)
		(value_assigned eleven twenty-two)
		(value_assigned eleven twenty-three)
		(value_assigned eleven twenty-four)
		(value_assigned eleven twenty-five)
		(value_assigned twelve one)
		(value_assigned twelve two)
		(value_assigned twelve three)
		(value_assigned twelve four)
		(value_assigned twelve five)
		(value_assigned twelve six)
		(value_assigned twelve seven)
		(value_assigned twelve eight)
		(value_assigned twelve nine)

		(value_assigned twelve ten)
		(value_assigned twelve eleven)
		(value_assigned twelve twelve)
		(value_assigned twelve thirteen)
		(value_assigned twelve fourteen)
		(value_assigned twelve fifteen)
		(value_assigned twelve sixteen)
		(value_assigned twelve seventeen)
		(value_assigned twelve eighteen)
		(value_assigned twelve nineteen)
		(value_assigned twelve twenty)
		(value_assigned twelve twenty-one)
		(value_assigned twelve twenty-two)
		(value_assigned twelve twenty-three)
		(value_assigned twelve twenty-four)
		(value_assigned twelve twenty-five)
		(value_assigned thirteen one)
		(value_assigned thirteen two)
		(value_assigned thirteen three)
		(value_assigned thirteen four)
		(value_assigned thirteen five)
		(value_assigned thirteen six)
		(value_assigned thirteen seven)
		(value_assigned thirteen eight)
		(value_assigned thirteen nine)

		(value_assigned thirteen ten)
		(value_assigned thirteen eleven)
		(value_assigned thirteen twelve)
		(value_assigned thirteen thirteen)
		(value_assigned thirteen fourteen)
		(value_assigned thirteen fifteen)
		(value_assigned thirteen sixteen)
		(value_assigned thirteen seventeen)
		(value_assigned thirteen eighteen)
		(value_assigned thirteen nineteen)
		(value_assigned thirteen twenty)
		(value_assigned thirteen twenty-one)
		(value_assigned thirteen twenty-two)
		(value_assigned thirteen twenty-three)
		(value_assigned thirteen twenty-four)
		(value_assigned thirteen twenty-five)
		(value_assigned fourteen one)
		(value_assigned fourteen two)
		(value_assigned fourteen three)
		(value_assigned fourteen four)
		(value_assigned fourteen five)
		(value_assigned fourteen six)
		(value_assigned fourteen seven)
		(value_assigned fourteen eight)
		(value_assigned fourteen nine)

		(value_assigned fourteen ten)
		(value_assigned fourteen eleven)
		(value_assigned fourteen twelve)
		(value_assigned fourteen thirteen)
		(value_assigned fourteen fourteen)
		(value_assigned fourteen fifteen)
		(value_assigned fourteen sixteen)
		(value_assigned fourteen seventeen)
		(value_assigned fourteen eighteen)
		(value_assigned fourteen nineteen)
		(value_assigned fourteen twenty)
		(value_assigned fourteen twenty-one)
		(value_assigned fourteen twenty-two)
		(value_assigned fourteen twenty-three)
		(value_assigned fourteen twenty-four)
		(value_assigned fourteen twenty-five)
		(value_assigned fifteen one)
		(value_assigned fifteen two)
		(value_assigned fifteen three)
		(value_assigned fifteen four)
		(value_assigned fifteen five)
		(value_assigned fifteen six)
		(value_assigned fifteen seven)
		(value_assigned fifteen eight)
		(value_assigned fifteen nine)

		(value_assigned fifteen ten)
		(value_assigned fifteen eleven)
		(value_assigned fifteen twelve)
		(value_assigned fifteen thirteen)
		(value_assigned fifteen fourteen)
		(value_assigned fifteen fifteen)
		(value_assigned fifteen sixteen)
		(value_assigned fifteen seventeen)
		(value_assigned fifteen eighteen)
		(value_assigned fifteen nineteen)
		(value_assigned fifteen twenty)
		(value_assigned fifteen twenty-one)
		(value_assigned fifteen twenty-two)
		(value_assigned fifteen twenty-three)
		(value_assigned fifteen twenty-four)
		(value_assigned fifteen twenty-five)
		(value_assigned sixteen one)
		(value_assigned sixteen two)
		(value_assigned sixteen three)
		(value_assigned sixteen four)
		(value_assigned sixteen five)
		(value_assigned sixteen six)
		(value_assigned sixteen seven)
		(value_assigned sixteen eight)
		(value_assigned sixteen nine)

		(value_assigned sixteen ten)
		(value_assigned sixteen eleven)
		(value_assigned sixteen twelve)
		(value_assigned sixteen thirteen)
		(value_assigned sixteen fourteen)
		(value_assigned sixteen fifteen)
		(value_assigned sixteen sixteen)
		(value_assigned sixteen seventeen)
		(value_assigned sixteen eighteen)
		(value_assigned sixteen nineteen)
		(value_assigned sixteen twenty)
		(value_assigned sixteen twenty-one)
		(value_assigned sixteen twenty-two)
		(value_assigned sixteen twenty-three)
		(value_assigned sixteen twenty-four)
		(value_assigned sixteen twenty-five)
		(value_assigned seventeen one)
		(value_assigned seventeen two)
		(value_assigned seventeen three)
		(value_assigned seventeen four)
		(value_assigned seventeen five)
		(value_assigned seventeen six)
		(value_assigned seventeen seven)
		(value_assigned seventeen eight)
		(value_assigned seventeen nine)

		(value_assigned seventeen ten)
		(value_assigned seventeen eleven)
		(value_assigned seventeen twelve)
		(value_assigned seventeen thirteen)
		(value_assigned seventeen fourteen)
		(value_assigned seventeen fifteen)
		(value_assigned seventeen sixteen)
		(value_assigned seventeen seventeen)
		(value_assigned seventeen eighteen)
		(value_assigned seventeen nineteen)
		(value_assigned seventeen twenty)
		(value_assigned seventeen twenty-one)
		(value_assigned seventeen twenty-two)
		(value_assigned seventeen twenty-three)
		(value_assigned seventeen twenty-four)
		(value_assigned seventeen twenty-five)
		(value_assigned eighteen one)
		(value_assigned eighteen two)
		(value_assigned eighteen three)
		(value_assigned eighteen four)
		(value_assigned eighteen five)
		(value_assigned eighteen six)
		(value_assigned eighteen seven)
		(value_assigned eighteen eight)
		(value_assigned eighteen nine)

		(value_assigned eighteen ten)
		(value_assigned eighteen eleven)
		(value_assigned eighteen twelve)
		(value_assigned eighteen thirteen)
		(value_assigned eighteen fourteen)
		(value_assigned eighteen fifteen)
		(value_assigned eighteen sixteen)
		(value_assigned eighteen seventeen)
		(value_assigned eighteen eighteen)
		(value_assigned eighteen nineteen)
		(value_assigned eighteen twenty)
		(value_assigned eighteen twenty-one)
		(value_assigned eighteen twenty-two)
		(value_assigned eighteen twenty-three)
		(value_assigned eighteen twenty-four)
		(value_assigned eighteen twenty-five)
		(value_assigned nineteen one)
		(value_assigned nineteen two)
		(value_assigned nineteen three)
		(value_assigned nineteen four)
		(value_assigned nineteen five)
		(value_assigned nineteen six)
		(value_assigned nineteen seven)
		(value_assigned nineteen eight)
		(value_assigned nineteen nine)

		(value_assigned nineteen ten)
		(value_assigned nineteen eleven)
		(value_assigned nineteen twelve)
		(value_assigned nineteen thirteen)
		(value_assigned nineteen fourteen)
		(value_assigned nineteen fifteen)
		(value_assigned nineteen sixteen)
		(value_assigned nineteen seventeen)
		(value_assigned nineteen eighteen)
		(value_assigned nineteen nineteen)
		(value_assigned nineteen twenty)
		(value_assigned nineteen twenty-one)
		(value_assigned nineteen twenty-two)
		(value_assigned nineteen twenty-three)
		(value_assigned nineteen twenty-four)
		(value_assigned nineteen twenty-five)
		(value_assigned twenty one)
		(value_assigned twenty two)
		(value_assigned twenty three)
		(value_assigned twenty four)
		(value_assigned twenty five)
		(value_assigned twenty six)
		(value_assigned twenty seven)
		(value_assigned twenty eight)
		(value_assigned twenty nine)

		(value_assigned twenty ten)
		(value_assigned twenty eleven)
		(value_assigned twenty twelve)
		(value_assigned twenty thirteen)
		(value_assigned twenty fourteen)
		(value_assigned twenty fifteen)
		(value_assigned twenty sixteen)
		(value_assigned twenty seventeen)
		(value_assigned twenty eighteen)
		(value_assigned twenty nineteen)
		(value_assigned twenty twenty)
		(value_assigned twenty twenty-one)
		(value_assigned twenty twenty-two)
		(value_assigned twenty twenty-three)
		(value_assigned twenty twenty-four)
		(value_assigned twenty twenty-five)
		(value_assigned twenty-one one)
		(value_assigned twenty-one two)
		(value_assigned twenty-one three)
		(value_assigned twenty-one four)
		(value_assigned twenty-one five)
		(value_assigned twenty-one six)
		(value_assigned twenty-one seven)
		(value_assigned twenty-one eight)
		(value_assigned twenty-one nine)

		(value_assigned twenty-one ten)
		(value_assigned twenty-one eleven)
		(value_assigned twenty-one twelve)
		(value_assigned twenty-one thirteen)
		(value_assigned twenty-one fourteen)
		(value_assigned twenty-one fifteen)
		(value_assigned twenty-one sixteen)
		(value_assigned twenty-one seventeen)
		(value_assigned twenty-one eighteen)
		(value_assigned twenty-one nineteen)
		(value_assigned twenty-one twenty)
		(value_assigned twenty-one twenty-one)
		(value_assigned twenty-one twenty-two)
		(value_assigned twenty-one twenty-three)
		(value_assigned twenty-one twenty-four)
		(value_assigned twenty-one twenty-five)
		(value_assigned twenty-two one)
		(value_assigned twenty-two two)
		(value_assigned twenty-two three)
		(value_assigned twenty-two four)
		(value_assigned twenty-two five)
		(value_assigned twenty-two six)
		(value_assigned twenty-two seven)
		(value_assigned twenty-two eight)
		(value_assigned twenty-two nine)

		(value_assigned twenty-two ten)
		(value_assigned twenty-two eleven)
		(value_assigned twenty-two twelve)
		(value_assigned twenty-two thirteen)
		(value_assigned twenty-two fourteen)
		(value_assigned twenty-two fifteen)
		(value_assigned twenty-two sixteen)
		(value_assigned twenty-two seventeen)
		(value_assigned twenty-two eighteen)
		(value_assigned twenty-two nineteen)
		(value_assigned twenty-two twenty)
		(value_assigned twenty-two twenty-one)
		(value_assigned twenty-two twenty-two)
		(value_assigned twenty-two twenty-three)
		(value_assigned twenty-two twenty-four)
		(value_assigned twenty-two twenty-five)
		(value_assigned twenty-three one)
		(value_assigned twenty-three two)
		(value_assigned twenty-three three)
		(value_assigned twenty-three four)
		(value_assigned twenty-three five)
		(value_assigned twenty-three six)
		(value_assigned twenty-three seven)
		(value_assigned twenty-three eight)
		(value_assigned twenty-three nine)

		(value_assigned twenty-three ten)
		(value_assigned twenty-three eleven)
		(value_assigned twenty-three twelve)
		(value_assigned twenty-three thirteen)
		(value_assigned twenty-three fourteen)
		(value_assigned twenty-three fifteen)
		(value_assigned twenty-three sixteen)
		(value_assigned twenty-three seventeen)
		(value_assigned twenty-three eighteen)
		(value_assigned twenty-three nineteen)
		(value_assigned twenty-three twenty)
		(value_assigned twenty-three twenty-one)
		(value_assigned twenty-three twenty-two)
		(value_assigned twenty-three twenty-three)
		(value_assigned twenty-three twenty-four)
		(value_assigned twenty-three twenty-five)
		(value_assigned twenty-four one)
		(value_assigned twenty-four two)
		(value_assigned twenty-four three)
		(value_assigned twenty-four four)
		(value_assigned twenty-four five)
		(value_assigned twenty-four six)
		(value_assigned twenty-four seven)
		(value_assigned twenty-four eight)
		(value_assigned twenty-four nine)

		(value_assigned twenty-four ten)
		(value_assigned twenty-four eleven)
		(value_assigned twenty-four twelve)
		(value_assigned twenty-four thirteen)
		(value_assigned twenty-four fourteen)
		(value_assigned twenty-four fifteen)
		(value_assigned twenty-four sixteen)
		(value_assigned twenty-four seventeen)
		(value_assigned twenty-four eighteen)
		(value_assigned twenty-four nineteen)
		(value_assigned twenty-four twenty)
		(value_assigned twenty-four twenty-one)
		(value_assigned twenty-four twenty-two)
		(value_assigned twenty-four twenty-three)
		(value_assigned twenty-four twenty-four)
		(value_assigned twenty-four twenty-five)
		(value_assigned twenty-five one)
		(value_assigned twenty-five two)
		(value_assigned twenty-five three)
		(value_assigned twenty-five four)
		(value_assigned twenty-five five)
		(value_assigned twenty-five six)
		(value_assigned twenty-five seven)
		(value_assigned twenty-five eight)
		(value_assigned twenty-five nine)

		(value_assigned twenty-five ten)
		(value_assigned twenty-five eleven)
		(value_assigned twenty-five twelve)
		(value_assigned twenty-five thirteen)
		(value_assigned twenty-five fourteen)
		(value_assigned twenty-five fifteen)
		(value_assigned twenty-five sixteen)
		(value_assigned twenty-five seventeen)
		(value_assigned twenty-five eighteen)
		(value_assigned twenty-five nineteen)
		(value_assigned twenty-five twenty)
		(value_assigned twenty-five twenty-one)
		(value_assigned twenty-five twenty-two)
		(value_assigned twenty-five twenty-three)
		(value_assigned twenty-five twenty-four)
		(value_assigned twenty-five twenty-five)
	)
)
